Add test cases for diffing changes to modules
NathanReb/ocaml-api-watch pull request #17
Opened 2024-03-07 07:58 UTC by Dezzy12

I have implemented the test cases for Adding, removing and modifying a module.
Fixes #10 

@NathanReb, @shonfeder, @dinakajoy

2024-03-07 09:43 UTC, NathanReb requested changes
It looks promising, you got how the cram test work right and properly generate the `.cmi` files and run the tool correctly but the test cases aren't correct at the moment.

I left a few comments to guide you on how to fix them.

Given `ref.mli` does not define any modules you should write a new `mod_ref.mli` that you would use as the reference for the diff in all of your tests, it would probably make them more readable.

2024-03-07 09:43 UTC, NathanReb commented on tests/api-diff/run.t
> +  > module Hello :
Here you're not simply adding a module compared to `ref.mli`, you're also removing the type and value that is there.

The test case should showcase a single change between the two `.cmi` files.

2024-03-07 09:43 UTC, NathanReb commented on tests/api-diff/run.t
> +  >     val to_string : t -> string
We don't need all this here and should keep the test case as simple as possible. Even an empty module signature should work here I guess:
```suggestion
```

2024-03-07 09:43 UTC, NathanReb commented on tests/api-diff/run.t
> +  $ cat > mod_remove.mli << EOF
Here you're just copying the original `ref.mli` file so you're not removing anything.

It's probably best if you define `mod_ref.mli` and `mod_ref.cmi` files that define a couple of modules so you can use them as a base for the three test cases here.

2024-03-07 09:43 UTC, NathanReb commented on tests/api-diff/run.t
> +  $ api-diff ref.cmi mod_modify.cmi
Same here, you need to make it so the only change between the first and second argument is a modification of an existing module.

2024-03-07 09:47 UTC, NathanReb commented
Remember to look at the CI checks to see if your PR builds correctly and is properly formatted.

When writing or editing tests you'll want to run `dune runtest` to see if it all works. You can read the [relevant part of the contributing guide]().

In particular here it should show an error, just as it did in #14. See https://github.com/NathanReb/ocaml-api-watch/pull/14#issuecomment-1982303593 for what to do with it!

2024-03-09 08:54 UTC, harshey1103 commented
The pull request has been open for an extended period, and @Dezzy12 hasn't been actively contributing to it. Would it be acceptable for me to take over and continue working on this pull request? @Dezzy12 @NathanReb @shonfeder
I would also get a chance to verify my work on https://github.com/NathanReb/ocaml-api-watch/pull/24.

2024-03-09 15:11 UTC, shonfeder commented
Let's give a bit of time for @Dezzy12 to reply with whether they still have the time and energy to see this thru. Thanks, @harshey1103!

2024-03-09 15:32 UTC, Dezzy12 commented
@harshey1103 please go ahead with it. Encountered some issues that I have to sort. So as not to hold down this issue for too long, you can have it if that's okay by @shonfeder

2024-03-09 15:36 UTC, shonfeder commented
@harshey1103, could you please comment on #10 so I can assign that issue to you (GitHub doesn't let us assign issues to people who haven't commented on them).

2024-03-09 21:51 UTC, shonfeder commented
Closing in favor of #25

2024-03-09 21:51 UTC, closed without merging